### ISSUE TITLE
Application exit if INI file does not exist

### ISSUE THREAD

**Issue by vaz-ar** [vharitonsky/iniflags#5]
When setting a file path with the SetConfigFile() function, the program will exit if the file does not exist.
Maybe the Parse() function could return an error if the file does not exist ?

**Comment by valyala** [comment]
iniflags.Parse() function doesn't return errors to be drop-in replacement to flag.Parse(). It cannot be modified to return errors, since it will break existing iniflags users, who expect application exit on ini files' errors.

Just check whether the file exists before calling SetConfigFile() and handle this case appropriately. For example, call SetConfigFile() only if the file exists or provide another ini file.
