### ISSUE TITLE
Application exit if "./" is missing for the -config flag

### ISSUE THREAD

**Issue by vaz-ar** [vharitonsky/iniflags#6]
if the config file is in the current folder, it won't work to run the following command:

`my_program -config config.ini`

the application exit with the exit status 1

**Comment by vharitonsky** [comment]
Thank you, I will see into it

**Comment by valyala** [comment]
Both cases work for me:

    $ ./my_program -config config.ini
    $ ./my_program -config ./config.ini

Note './' before the program - if you miss it, then the program may start from arbitrary folder, which may be identified by:

    $ which my_program

Iniflags has special handling for config paths, which don't start with '/' and './' - is searches for config file  at the program's location. For example:

    $ /path/to/my/program -config cfg/config.ini

In this case iniflags searches for config.ini not in the `pwd`/cfg/config.ini , but in the /path/to/my/program/cfg/config.ini . This makes startup strings shorter, because there is no need in duplicating full path to program in the path to -config.

**Comment by vaz-ar** [comment]
My program is installed via `go install`, so I have no reason to start it with `./`, but I understand the problem
